### PR TITLE
Add spanish translation

### PR DESCRIPTION
**Pull request by mcroad**
Spanish translation should be ready. I haven't been able to test it. When I try to install dependencies, it fails saying:

```
Because anytime depends on flutter_localizations any from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because anytime depends on intl ^0.16.0, version solving failed.    
Running "flutter pub get" in anytime_podcast_player...                  
pub get failed (1; So, because anytime depends on intl ^0.16.0, version solving failed.)
```
Since I was not able to install the necessary dependencies, I can't generate the dart code from the ARB files. Am I missing something as to why packages don't install?

Once I am able to resolve the issue, I'll update the PR with the generated files.

Related to breez/breezmobile#464

### CODE REVIEW

**Comment by mcroad** [comment]
cc @roeierez @kingonly

**Comment by roeierez** [comment]
> Once I am able to resolve the issue, I'll update the PR with the generated files.

Hey @mcroad the master branch is reserved for synching with anytime original repository. 
The branch we are using in Breez is "breez_merge" so you will need to rebase your changes on top of that branch.
Sorry for not being clear on that.

**Comment by mcroad** [comment]
All good. Consider making `breez_merge` the default branch.

**Comment by mcroad** [comment]
Closed in favor of #24

**Pull request closed without merging**
